name: Run Tests

on: [push, pull_request]

jobs:

  test-library:
    uses: quattor/release/.github/workflows/vanilla-scdb.yaml@main

  standard-pan:
    uses: quattor/release/.github/workflows/pan-template-tests.yaml@main

  test-templates:
    runs-on: ubuntu-latest
    container: ghcr.io/quattor/quattor-test-container:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test templates
      run: .ci-scripts/test-templates
